[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; CPU Configuration
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; Flash Configuration
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB


; PSRAM Configuration
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=5
    -mfix-esp32-psram-cache-issue

; Upload Configuration
upload_speed = 921600
monitor_speed = 115200

lib_deps = 
	MicroTFLite@1.0.4
    fastled/FastLED@^3.6.0
    ; tecnically other, but PaltformIO should detect those autonomisilly
    ; FS @ 2.0.0
    ; SD_MMC @ 2.0.0